# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backblog', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
